### Naive Bayes 

In [ ]:
'''The Naïve Bayes classifier is a supervised machine learning algorithm that is used for classification tasks 
such as text classification. They use principles of probability to perform classification tasks.'''

In [ ]:
# Gaussian Naive Bayes

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

/Users/sneha/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [3]:
po = pd.read_csv('titanic.csv')
po.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [4]:
po.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
po.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [6]:
new_po = po.drop('Survived',axis='columns')
target = po.Survived

In [7]:
new_po.Sex = new_po.Sex.map({'male':1, 'female':2})

In [9]:
dummies = pd.get_dummies(new_po.Sex, dtype=int)
dummies.head()

1  2
0  1  0
1  0  1
2  0  1
3  0  1
4  1  0

In [10]:
df = pd.concat([new_po,dummies], axis='columns')
df.head(3)

Pclass  Sex   Age     Fare  1  2
0       3    1  22.0   7.2500  1  0
1       1    2  38.0  71.2833  0  1
2       3    2  26.0   7.9250  0  1

In [19]:
new_df = df.drop(['Sex',1], axis='columns')
new_df.head()

Pclass   Age     Fare  2
0       3  22.0   7.2500  0
1       1  38.0  71.2833  1
2       3  26.0   7.9250  1
3       1  35.0  53.1000  1
4       3  35.0   8.0500  0

In [20]:
dict = {2:'female'}

In [102]:
new_df.rename(columns=dict, inplace=True)
new_df.head(11)

Pclass        Age     Fare  female
0        3  22.000000   7.2500       0
1        1  38.000000  71.2833       1
2        3  26.000000   7.9250       1
3        1  35.000000  53.1000       1
4        3  35.000000   8.0500       0
5        3  29.699118   8.4583       0
6        1  54.000000  51.8625       0
7        3   2.000000  21.0750       0
8        3  27.000000  11.1333       1
9        2  14.000000  30.0708       1
10       3   4.000000  16.7000       1

In [24]:
new_df.isnull().sum()

Pclass      0
Age       177
Fare        0
female      0
dtype: int64

In [25]:
new_df.Age = new_df.Age.fillna(new_df.Age.mean())
new_df.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [26]:
new_df.isnull().sum()

Pclass    0
Age       0
Fare      0
female    0
dtype: int64

In [36]:
x_train, x_test, y_train, y_test = train_test_split(new_df,target,test_size=0.25)

In [37]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [38]:
model.fit(x_train,y_train)

GaussianNB()

In [39]:
model.score(x_test,y_test)

0.7623318385650224

In [41]:
model.predict(x_test[0:10])

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [43]:
model.predict_proba(x_test[:10])

array([[0.9387174 , 0.0612826 ],
       [0.97079892, 0.02920108],
       [0.96791119, 0.03208881],
       [0.97146568, 0.02853432],
       [0.01046114, 0.98953886],
       [0.93812318, 0.06187682],
       [0.96758875, 0.03241125],
       [0.42205936, 0.57794064],
       [0.94046991, 0.05953009],
       [0.93502622, 0.06497378]])

In [44]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),x_train, y_train, cv=5)

array([0.75373134, 0.78358209, 0.79104478, 0.81203008, 0.76691729])

In [ ]:
# Multinomial Naive Bayes

In [45]:
lo = pd.read_csv('spam.csv')
lo.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [46]:
lo.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [48]:
lo['spam'] = lo['Category'].apply(lambda x: 1 if x=='spam' else 0)
lo.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [49]:
a_train, a_test, b_train, b_test = train_test_split(lo.Message,lo.spam)

In [51]:
# It separates each word and counts it accordingly
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
a_train_count = v.fit_transform(a_train.values)
a_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [52]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(a_train_count,b_train)

MultinomialNB()

In [53]:
a_test_count = v.transform(a_test)
model.score(a_test_count, b_test)

0.9856424982053122

In [54]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [55]:
clf.fit(a_train, b_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [56]:
clf.score(a_test,b_test)

0.9856424982053122

### L1 and L2 Regularization

In [57]:
# Hyper parameter tunning using gridsearch

In [ ]:
''' L1 and L2 regularization are techniques used in machine learning to improve model generalization and reduce
overfitting.

L1 Regularization: Also called a lasso regression, adds the absolute value of the sum 
(“absolute value of magnitude”) of coefficients as a penalty term to the loss function.

L2 Regularization: Also called a ridge regression, adds the squared sum (“squared magnitude”) of coefficients 
as the penalty term to the loss function.

In [58]:
kj = pd.read_csv('./Melbourne_housing_FULL.csv')
kj.head()

Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St      2    h        NaN     SS  Jellis   
1  Abbotsford        85 Turner St      2    h  1480000.0      S  Biggin   
2  Abbotsford     25 Bloomburg St      2    h  1035000.0      S  Biggin   
3  Abbotsford  18/659 Victoria St      3    u        NaN     VB  Rounds   
4  Abbotsford        5 Charles St      3    h  1465000.0     SP  Biggin   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/09/2016       2.5    3067.0  ...       1.0  1.0     126.0           NaN   
1  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
2  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
3  4/02/2016       2.5    3067.0  ...       2.0  1.0       0.0           NaN   
4  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   

   YearBuilt         CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN  Yarra City Council  -37.8014    144.9958  Northern Metropolitan   
1        NaN  Yarra City Council  -37.7996    144.9984  Northern Metropolitan   
2     1900.0  Yarra City Council  -37.8079    144.9934  Northern Metropolitan   
3        NaN  Yarra City Council  -37.8114    145.0116  Northern Metropolitan   
4     1900.0  Yarra City Council  -37.8093    144.9944  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [59]:
kj.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [60]:
cols_to_use = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount', 
               'Distance', 'CouncilArea', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']
kj = kj[cols_to_use]

In [61]:
kj.head()

Suburb  Rooms Type Method SellerG             Regionname  \
0  Abbotsford      2    h     SS  Jellis  Northern Metropolitan   
1  Abbotsford      2    h      S  Biggin  Northern Metropolitan   
2  Abbotsford      2    h      S  Biggin  Northern Metropolitan   
3  Abbotsford      3    u     VB  Rounds  Northern Metropolitan   
4  Abbotsford      3    h     SP  Biggin  Northern Metropolitan   

   Propertycount  Distance         CouncilArea  Bedroom2  Bathroom  Car  \
0         4019.0       2.5  Yarra City Council       2.0       1.0  1.0   
1         4019.0       2.5  Yarra City Council       2.0       1.0  1.0   
2         4019.0       2.5  Yarra City Council       2.0       1.0  0.0   
3         4019.0       2.5  Yarra City Council       3.0       2.0  1.0   
4         4019.0       2.5  Yarra City Council       3.0       2.0  0.0   

   Landsize  BuildingArea      Price  
0     126.0           NaN        NaN  
1     202.0           NaN  1480000.0  
2     156.0          79.0  1035000.0  
3       0.0           NaN        NaN  
4     134.0         150.0  1465000.0

In [63]:
kj.shape

(34857, 15)

In [64]:
kj.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        3
Distance             1
CouncilArea          3
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [66]:
cols_to_fill_zero = ['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']
kj[cols_to_fill_zero] = kj[cols_to_fill_zero].fillna(0)

In [68]:
kj['Landsize'] = kj['Landsize'].fillna(kj.Landsize.mean())
kj['BuildingArea'] = kj['BuildingArea'].fillna(kj.BuildingArea.mean())

In [69]:
kj.isnull().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          3
Propertycount       0
Distance            0
CouncilArea         3
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
Price            7610
dtype: int64

In [70]:
kj.shape

(34857, 15)

In [71]:
kj.dropna(inplace=True)

In [72]:
kj.shape

(27244, 15)

In [73]:
kj.head()

Suburb  Rooms Type Method SellerG             Regionname  \
1  Abbotsford      2    h      S  Biggin  Northern Metropolitan   
2  Abbotsford      2    h      S  Biggin  Northern Metropolitan   
4  Abbotsford      3    h     SP  Biggin  Northern Metropolitan   
5  Abbotsford      3    h     PI  Biggin  Northern Metropolitan   
6  Abbotsford      4    h     VB  Nelson  Northern Metropolitan   

   Propertycount  Distance         CouncilArea  Bedroom2  Bathroom  Car  \
1         4019.0       2.5  Yarra City Council       2.0       1.0  1.0   
2         4019.0       2.5  Yarra City Council       2.0       1.0  0.0   
4         4019.0       2.5  Yarra City Council       3.0       2.0  0.0   
5         4019.0       2.5  Yarra City Council       3.0       2.0  1.0   
6         4019.0       2.5  Yarra City Council       3.0       1.0  2.0   

   Landsize  BuildingArea      Price  
1     202.0      160.2564  1480000.0  
2     156.0       79.0000  1035000.0  
4     134.0      150.0000  1465000.0  
5      94.0      160.2564   850000.0  
6     120.0      142.0000  1600000.0

In [88]:
new1_kj = pd.get_dummies(kj, dtype=int)

In [89]:
new1_kj.head()

Rooms  Propertycount  Distance  Bedroom2  Bathroom  Car  Landsize  \
1      2         4019.0       2.5       2.0       1.0  1.0     202.0   
2      2         4019.0       2.5       2.0       1.0  0.0     156.0   
4      3         4019.0       2.5       3.0       2.0  0.0     134.0   
5      3         4019.0       2.5       3.0       2.0  1.0      94.0   
6      4         4019.0       2.5       3.0       1.0  2.0     120.0   

   BuildingArea      Price  Suburb_Aberfeldie  ...  \
1      160.2564  1480000.0              False  ...   
2       79.0000  1035000.0              False  ...   
4      150.0000  1465000.0              False  ...   
5      160.2564   850000.0              False  ...   
6      142.0000  1600000.0              False  ...   

   CouncilArea_Moorabool Shire Council  CouncilArea_Moreland City Council  \
1                                False                              False   
2                                False                              False   
4                                False                              False   
5                                False                              False   
6                                False                              False   

   CouncilArea_Nillumbik Shire Council  CouncilArea_Port Phillip City Council  \
1                                False                                  False   
2                                False                                  False   
4                                False                                  False   
5                                False                                  False   
6                                False                                  False   

   CouncilArea_Stonnington City Council  CouncilArea_Whitehorse City Council  \
1                                 False                                False   
2                                 False                                False   
4                                 False                                False   
5                                 False                                False   
6                                 False                                False   

   CouncilArea_Whittlesea City Council  CouncilArea_Wyndham City Council  \
1                                False                             False   
2                                False                             False   
4                                False                             False   
5                                False                             False   
6                                False                             False   

   CouncilArea_Yarra City Council  CouncilArea_Yarra Ranges Shire Council  
1                            True                                   False  
2                            True                                   False  
4                            True                                   False  
5                            True                                   False  
6                            True                                   False  

[5 rows x 745 columns]

In [90]:
x = new1_kj.drop('Price', axis=1)
y = new1_kj['Price']

In [91]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=2)

In [92]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [93]:
reg.score(x_train,y_train)

0.6827792395792723

In [101]:
reg.score(x_test, y_test)

0.13853683161729224

In [95]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha=50, max_iter=100, tol=0.1)
lasso_reg.fit(x_train, y_train)

/Users/sneha/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.327e+15, tolerance: 7.963e+14
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=50, max_iter=100, tol=0.1)

In [96]:
lasso_reg.score(x_test, y_test)

0.6636111369404492

In [97]:
lasso_reg.score(x_train,y_train)

0.6766985624766824

In [98]:
from sklearn.linear_model import Ridge
ridge_reg= Ridge(alpha=50, max_iter=100, tol=0.1)
ridge_reg.fit(x_train,y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [99]:
ridge_reg.score(x_train,y_train)

0.6622376739684328

In [100]:
ridge_reg.score(x_test,y_test)

0.6670848945194959